name: Build Snapshot

on:
  push:
    branches-ignore:
      - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 7 (fails from toolchain)
        uses: actions/setup-java@v4
        with:
          java-version: '7'
          distribution: 'zulu'

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Publish
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
        run: ./gradlew publish -Pversion_snapshot -Pmvn.user=${{ secrets.MAVEN_USER }} -Pmvn.key=${{ secrets.MAVEN_TOKEN }}

      - uses: actions/upload-artifact@v2
        with:
          name: base
          path: build/libs

      - uses: actions/upload-artifact@v2
        with:
          name: api
          path: java-api/build/libs

      - uses: actions/upload-artifact@v2
        with:
          name: gradle
          path: gradle-plugin/build/libs